# -- 코드를 입력하세요
# SELECT ANIMAL_ID, NAME
# FROM ANIMAL_INS 
# WHERE ANIMAL_TYPE = 'Dog' AND LOWER(NAME) LIKE '%el%'
# ORDER BY NAME ASC;




SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS 
WHERE (NAME LIKE '%EL%' or NAME LIKE '%el%')
AND ANIMAL_TYPE = 'Dog'
ORDER BY NAME ASC;
