/*
대장균 크기 내림차순 정렬 시, 
CRITICAL : 0 - 25
HIGH : 51 - 75
MEDIUM: 76 - 100
ID, COLONY_NAME 출력
*/
WITH RANKED AS (
    SELECT ID,
        NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS TILE
    FROM ECOLI_DATA 
)
SELECT 
    ID,
    CASE TILE
        WHEN 1 THEN 'CRITICAL'
        WHEN 2 THEN 'HIGH'
        WHEN 3 THEN 'MEDIUM'
        WHEN 4 THEN 'LOW'
    END AS COLONY_NAME
FROM RANKED
ORDER BY ID;