WITH RECURSIVE GENERATION_CTE AS (
    -- 1. 최초 개체 (PARENT_ID가 NULL인 경우) → 1세대
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    -- 2. 재귀적으로 자식 개체 추적 → 세대 + 1씩 증가
    SELECT E.ID, G.GENERATION + 1
    FROM ECOLI_DATA E
    JOIN GENERATION_CTE G ON E.PARENT_ID = G.ID
),

-- 3. 자식이 없는 ID만 찾기
LEAF_CTE AS (
    SELECT G.ID, G.GENERATION
    FROM GENERATION_CTE G
    LEFT JOIN ECOLI_DATA E ON G.ID = E.PARENT_ID
    WHERE E.ID IS NULL
)

-- 4. 세대별로 개수 세기
SELECT COUNT(*) AS COUNT, GENERATION
FROM LEAF_CTE
GROUP BY GENERATION
ORDER BY GENERATION;
