/*
2022년 4월 13일 
최소되지 않은 CS 진료 예약 내역 조회
예악취소여부 APNT_CNCL_YN
*/
# SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
# FROM PATIENT P
# JOIN APPOINTMENT A ON P.PT_NO = A.PT_NO
# JOIN DOCTOR D ON D.MCDP_CD = A.MCDP_CD
# WHERE DATE_FORMAT(APNT_YMD,'%Y-%m-%d') = '2022-04-13' 
# GROUP BY A.APNT_CNCL_YN = 'N'
SELECT 
    A.APNT_NO, 
    P.PT_NAME, 
    P.PT_NO, 
    A.MCDP_CD, 
    D.DR_NAME, 
    A.APNT_YMD
FROM APPOINTMENT A
JOIN PATIENT P ON A.PT_NO = P.PT_NO
JOIN DOCTOR D ON A.MDDR_ID = D.DR_ID
WHERE DATE(A.APNT_YMD) = '2022-04-13'
  AND A.MCDP_CD = 'CS'
  AND A.APNT_CNCL_YN = 'N'
ORDER BY A.APNT_YMD ASC;

