/*
2022년 가장 평가 점수 높은 사원 찾기
상하반기 합 AS SCORE
*/
SELECT SUM(G.SCORE) AS SCORE,
E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES E
JOIN HR_GRADE G ON E.EMP_NO = G.EMP_NO
GROUP BY E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
ORDER BY SCORE DESC
LIMIT 1;
